APPLICATION ?= tests_$(notdir $(patsubst %/,%,$(CURDIR)))

ifneq (,$(wildcard $(CURDIR)/tests/.))
  DEFAULT_MODULE += test_utils_interactive_sync
endif

CFLAGS += -fprofile-arcs -ftest-coverage -fprofile-abs-path -lgcov -coverage -fPIC -DCONFIG_SKIP_BOOT_MSG
LINKFLAGS += -fprofile-arcs -ftest-coverage -fprofile-abs-path -lgcov -coverage -fPIC

ifneq (,$(filter tests_driver_%,$(APPLICATION)))
  BOARD ?= samr21-xpro
endif
BOARD ?= native
RIOTBASE ?= $(CURDIR)/../..
QUIET ?= 1
# DEVELHELP enabled by default for all tests, set 0 to disable
DEVELHELP ?= 1
